### ISSUE TITLE
Jest 26 support 

### ISSUE THREAD

**Issue by wldcordeiro** [jest-community/jest-watch-toggle-config#1]
It appears that in Jest 26 this no longer shows as a command key in watch mode. Additionally yarn warns about the dependency version mismatch from the major update.

**Comment by tdd** [comment]
Hey @wldcordeiro sorry I hadn't noticed this issue earlier…

I'm not quite sure what you mean… I just pushed a 2.0.1 version that is all up-to-date on deps. The peerDeps still allows Jest 23.4.1+ tho.

Could you please grab the latest version, try to reproduce, and either close this or provide further details / reproducible steps for your problem if it persists?

Thanks!

**Comment by wldcordeiro** [comment]
@tdd my issue was opened back in May. Your releases were in July so if you fixed it in the 2.x range that was after my issue was opened.

**Comment by tdd** [comment]
@wldcordeiro alright! Do you still face issues now then?

**Comment by unional** [comment]
I can confirm it is working. This issue can be closed.
