### ISSUE TITLE
The peer deps of `jest-validate` not needed.

### ISSUE THREAD

**Issue by unional** [jest-community/jest-watch-toggle-config#19]
The peer deps of `jest-validate` is actually not needed.

`jest-validate` will always present in the consuming repo since `jest` transiently include it as dep:

`jest -> jest-cli -> jest-validate`

https://github.com/facebook/jest/blob/main/packages/jest/package.json
https://github.com/facebook/jest/blob/main/packages/jest-cli/package.json

This will get rid of the unnecessary peer dep warning.

**Comment by unional** [comment]
Hi @tdd, is this project still being maintained? I would happy to contribute.

**Comment by unional** [comment]
For anyone getting here, I have forked the repo and release `jest-watch-toggle-config-2` with this fix.

It is also used in [@repobuddy/jest](https://github.com/repobuddy/jest)

**Comment by SimenB** [comment]
I don't have access on npm, so not much I can do. @tdd could you grant me that?

https://www.npmjs.com/~simenb

**Comment by tdd** [comment]
Hi all, sorry for the limbo, I hadn't received any GitHub notification on this (or any other PRs for that matter 👀).

I'll be scheduling time to look at this particular issue and matching PR, then other PRs, this week. Expect some movement, finally!

Sorry about that.

**Comment by tdd** [comment]
Hey all! 👋🏻

So I just released v3.0.0, which has fully-updated deps, uses native ESM (but doesn't require user codebases to), and removed the jest-validate dep in the process.

I hope this addresses all your concerns!

Cheers!
